import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';
import { requestId, requestLogger } from './middleware/requestLogger.js';
import { healthRouter } from './routes/health.routes.js';
import { quotesRouter } from './routes/quotes.routes.js';
import { treasuryRouter } from './routes/treasury.routes.js';
import { analysisRouter } from './routes/analysis.routes.js';
import { snapshotsRouter } from './routes/snapshots.routes.js';
import { evidenceRouter } from './routes/evidence.routes.js';
const allowedOrigins = env.FRONTEND_ORIGIN.split(',').map((origin) => origin.trim()).filter(Boolean);
const app = express();
app.disable('x-powered-by');
app.use(requestId, requestLogger, helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.includes(origin)) callback(null, true); else callback(new Error('Origin is not allowed by CORS.')); }, methods: ['GET', 'POST', 'PUT'], allowedHeaders: ['Content-Type', 'X-Request-Id'] }));
app.use(express.json({ limit: '100kb' }));
app.use('/api', healthRouter, quotesRouter, treasuryRouter, analysisRouter, snapshotsRouter, evidenceRouter);
app.use(notFound, errorHandler);
export default app;
