import { Router } from 'express';
import * as controller from '../controllers/treasury.controller.js';
import { validateBody } from '../middleware/validate.js';
import { treasurySchema, treasuryUpdateSchema } from '../schemas/treasury.schema.js';
import { snapshotRequestSchema } from '../schemas/analysis.schema.js';
export const treasuryRouter = Router();
treasuryRouter.route('/treasuries').get(controller.list).post(validateBody(treasurySchema), controller.create);
treasuryRouter.route('/treasuries/:treasuryId').get(controller.get).put(validateBody(treasuryUpdateSchema), controller.update);
treasuryRouter.post('/treasuries/:treasuryId/archive', controller.archive);
treasuryRouter.post('/treasuries/:treasuryId/analyze', validateBody(snapshotRequestSchema), controller.analyze);
